# Change these first
owner: AipNooBest # Your GitHub organization or username, where this repository lives
repo: aksuma-uptime # The name of this repository

sites:
  - name: Main Site
    url: https://aksuma.ru/
  - name: Osu Server (Frontend)
    url: https://osu.aksuma.ru/
  - name: Osu Server (Backend)
    url: https://c.aksuma.ru/
  - name: Wiki
    url: https://wiki.aksuma.ru/
  - name: File Storage
    url: https://fs.aksuma.ru/
  - name: Gitea
    url: https://git.aksuma.ru/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aksuma.ru
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Aksuma Services Status
  introTitle: "Статус публичных сервисов Аксумы"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
